version: '3.1'
services:
  stats-server:
    build: stats/server
    image: server
    container_name: stats-server
    ports:
      - "9090:9090"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
    networks:
      - backend
      - databases
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
    env_file:
      - ".env"

  stats-db:
    build: stats-db
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "5342:5342"
    networks:
      - databases
    environment:
      - POSTGRES_DB=stats-db
    env_file:
      - ".env"

  ewm-service:
    build: emw-service
    image: service
    container_name: emw-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    networks:
      - frontend
      - backend
      - databases
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/emw-db
    env_file:
      - ".env"

  ewm-db:
    build: emw-db
    image: postgres:14-alpine
    container_name: emw-db
    networks:
      - databases
    env_file:
      - ".env"


networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  databases:
    driver: bridge